apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: g9ho3wilj-nodejs-gitops
  description: This is GitOps manifest for g9ho3wilj-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=g9ho3wilj-nodejs
    backstage.io/kubernetes-id: g9ho3wilj-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: g9ho3wilj-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:g9ho3wilj-nodejs
