apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g9ho3wilj-nodejs
  janus-idp.io/tekton: g9ho3wilj-nodejs
  backstage.io/kubernetes-id: g9ho3wilj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g9ho3wilj-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
